---
# tasks file for python
  - name: Install Python 3
    apt:
      name: python3
      state: latest
      update_cache: yes

  - name: Set Python3 as Default Python
    shell: update-alternatives --install /usr/bin/python python /usr/bin/python3 10

  - name: Install Pip3
    apt:
      name: python3-pip
      state: latest
      update_cache: yes

  - name: Set Pip3 as Default Pip
    shell: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
